### PR TITLE
Avif support refactoring and JPEG XL support

### PR DESCRIPTION
**Pull request by Antonytm**
1. Make next-gen image formats handling more generic. For adding a new format it should be enough to write one optimizer, write tests and add a configuration file.
2. Refactoring Avif support implementation. (e.g. added Copywrite, fixed MediaRequestHandler.cs, etc.)
3. Added JPEG XL optimizer
4. Changed way of CDN configuration works. Here is the trade-off: see `GenerateCacheKey.cs`. That pipeline will be called even if CDN is not enabled, but execution will be skipped if CDN is not enabled. It is done to make configuration less complex.
5. Updated readme.md

### CODE REVIEW

**Comment by Antonytm** [comment]
Hi @markgibbons25,

This PR contains a lot of changes making adoption of the new next-gen formats easier.
I will make additional testing for different configurations to make sure that all scenarios work.

But meanwhile, can you please take a look at a whole approach in general and let me know your thoughts?

**Comment by markgibbons25** [comment]
Looks perfect thanks! I can't see any issues :) Will release as v6 alpha.

**Comment by Antonytm** [comment]
I see that `Antonytm:feature/avif` based on `kamsar:feature/avif` in behind of `kamsar:master`.
I will merge them, and fix conflicts.

**Comment by markgibbons25** [comment]
Ah I didn't see this till now but I have resolved it, but let me know if I
missed anything.

**Pull request merged**
