### PR TITLE
Enable WebP optimization

### PR DESCRIPTION
**Pull request by Antonytm**
WebP is promising format that allows good optimization comparing to JPEG and PNG. It is supported in Chrome and Opera. Pull request allows to enable usage of WebP format for browsers that support this format.

### CODE REVIEW

**Comment by Antonytm** [comment]
Today figure out that even Akamai CDN has similar option: return WebP for Chrome. :-)

**Comment by kamsar** [comment]
At first glance, looks pretty nice. Thanks for the contribution.

Before I merge it I'll have to give it a deeper try, and that may take a bit so I appreciate your patience :)

**Comment by mr-grant** [comment]
Hi @kamsar, 
Could you merge this pull request?

**Comment by igor-evstratov** [comment]
Hi @kamsar,

Could you please push the new release to nuget?

**Pull request merged**
