### PR TITLE
Added jpegoptim lossy (quality 90%) optimizer

### PR DESCRIPTION
**Pull request by bartlomiejmucha**
I added this for my own project needs, because google page speed now suggest images to compress lossly. In my case google suggested that images on my site could be compressed by additional 500kb each, and 6MBs in total (yeah there are a lot of high quality images on site). Google suggest to use jpegtran or jpegoptim. The latter have option to set jpeg quality. I tested and I got the same results like google suggest with quality 90%. So the image is compressed from 700kb (the size after jpegtran) to 200kb and it looks the same.

### CODE REVIEW

**Comment by vellemansf** [comment]
Works like a charm!

**Comment by bartlomiejmucha** [comment]
How you disabled Sitecore's compressing?

**Comment by cmejiasr** [comment]
Works Perfect.

I had to down the quality a little bit more, but the results were the expected.

**Comment by bartlomiejmucha** [comment]
Google Page Speed suggest 85% quality. At first, I set it to 90% but now I'm considering to lower it to 85%.

**Pull request merged**
