### PR TITLE
Solve the issue with Temporary Files and refactor the PngOptimizer class

### PR DESCRIPTION
**Pull request by patocl**
Hi Kamsar,

I'm using and like your Dianoga project and I will like you accept my pull request.

It solve the issue **Lot of temp files getting created on the server for PNG Optimizer**
#14 opened 7 days ago by KunalGanatra 

Kind regards
patocl

### CODE REVIEW

**Comment by kamsar** [comment]
Can you outline what you did in terms of the refactor and the fix? There are enough changes in the diff to make it hard to know what was done why.

Once I understand what you're doing here I'm fine with accepting the PR :)

**Comment by patocl** [comment]
Hi, @kamsar 

To accomplish the issue, I feel the necessity to refactor a bit the code

**First Refactor**

- Move the _NativeMethods_ class to another file, because even it was being used just on PngOptimizer, it's could be a subclass of _DynamicLinkLibrary_.  (in a new namespace)

**Second Refactor**

- Extract and separate all implementation related to use external libraries into _DynamicLinkLibrary_ with unmanaged code.

- Create a _LoadMethodOrFunction_ method to load function or method from a module, validating that it exists and return a valid pointer.

**Solution**

- The _DynamicLinkLibrary_ class is responsible for loading and unloading the module and delete temporary files that are created.

- The _HostingEnvironment.MapPath()_ method need be stored into a field, to be used on Dispose method to delete this file.

**Pros**
- The _PngOptimizer_ class, now it's free and without dependencies with unmanaged code.
- In futures implementations of the _OptimizeProcessor_ base class, it can reuse this new _DynamicLinkLibrary_ class features.

**Notes**
At the moment is not necessary to include DI for the _DinamicLinkLibrary_ class because no want does over-engineering.

Kind regards, ;)

**Comment by patocl** [comment]
Sorry, I clicked the wrong button :)

**Comment by patocl** [comment]
Wow!!! I feel happy.

**Comment by kamsar** [comment]
This is now part of Dianoga 3.0.2.

**Pull request merged**
