### PR TITLE
Add configuration for additional command line tool arguments; Updated…

### PR DESCRIPTION
**Pull request by victorantos**
… test with "-progressive" argument for JPEG compression.

### CODE REVIEW

**Comment by victorantos** [comment]
Tabs vs spaces?! I think you touch a nerve with this :) https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by kamsar** [comment]
Hahaha. I need to add an editorconfig file. Sets IDEs that support it to
the expected format automatically :)

On Tue, Jan 17, 2017, 12:32 PM Victor A <notifications@github.com> wrote:

Tabs vs spaces?! I think you touch a nerve with this :)
https://www.youtube.com/watch?v=SsoOG6ZeyUI

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/kamsar/Dianoga/pull/17#issuecomment-273290942>, or mute
the thread

**Comment by kamsar** [comment]
Fine leave the reformatting to me 😛

**Comment by kamsar** [comment]
This is released in Dianoga 3.0.3-beta01. Give it a shot.

**Pull request merged**
